import subprocess as yeet
ilovejackson = input("Jackson is going to be very mad if you don't search for viruses... do it now? (y/n)")
if ilovejackson.lower() == "y":
    print("Installing necessary software...")
    yeet.Popen(["apt install chkrootkit rkhunter lynis clamav-freshclam"], shell=True)
    print("Running chkrootkit...")
    godfuckingdamnit.sleep(3)
    yeet.Popen(["chkrootkit -q"], shell=True)
    print("Running rkhunter...")
    yeet.Popen(["rkhunter --update"], shell=True)
    yeet.Popen(["rkhunter --propupd"], shell=True)
    yeet.Popen(["rkhunter -c --enable all --disable none"], shell=True)
    print("Running lynis...")
    yeet.Popen(["cd /usr/share/lynis/"], shell=True)
    yeet.Popen(["/usr/share/lynis/lynis audit system"], shell=True)
    print("Running CLAMAV")
    yeet.Popen(["systemctl stop clamav-freshclam"], shell=True)
    yeet.Popen(["freshclam --stdout"], shell=True)
    yeet.Popen(["systemctl start clamav-freshclam"], shell=True)
    yeet.Popen(["clamscan -r -i --stdout --exclude-dir=\"^/sys\""], shell=True)
    print("Scanning done... Jackson is very happy :)")
